server:
  port: 9098
spring:
  application:
    name: Fintech-service
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: Cool@123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true