server:
  port: 9097
spring:
  application:
    name: User-service
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: Sudeshna@06
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true